### ISSUE TITLE
Problem to using appcache_fallback_files

### ISSUE THREAD

**Issue by prabhugade** [realityforge/gwt-appcache#11]
Hi,
 I have added <extend-configuration-property name="appcache_fallback_files" value="time offline_time.txt"/> in gwt.xml then it showing following error at compile time

Buildfile: /home/prabhu/workspace/projects-2015/GWTOff/src/com/test/build.xml
gwt-compile:
     [java] Loading inherited module 'com.test.GWTOff'
     [java]    [ERROR] The property appcache_fallback_files must already exist as a configuration property
     [java]    [ERROR] Line 30: Unexpected exception while processing element 'extend-configuration-property'
     [java] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefSchema$BodySchema.__extend_configuration_property_begin(ModuleDefSchema.java:432)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:606)
     [java] 	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:230)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:294)
     [java] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
     [java] 	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
     [java] 	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
     [java] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
     [java] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
     [java] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
     [java] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
     [java] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
     [java] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
     [java] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
     [java] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:347)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:346)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:267)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:210)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:170)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:145)
     [java] 	at com.google.gwt.dev.Compiler.run(Compiler.java:129)
     [java] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:99)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
     [java] 	at com.google.gwt.dev.Compiler.main(Compiler.java:106)
     [java]    [ERROR] Failure while parsing XML
     [java] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
     [java] 	at com.google.gwt.dev.util.xml.DefaultSchema.onHandlerException(DefaultSchema.java:58)
     [java] 	at com.google.gwt.dev.util.xml.Schema.onHandlerException(Schema.java:66)
     [java] 	at com.google.gwt.dev.util.xml.Schema.onHandlerException(Schema.java:66)
     [java] 	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:240)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:294)
     [java] 	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
     [java] 	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
     [java] 	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
     [java] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
     [java] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
     [java] 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
     [java] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
     [java] 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
     [java] 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
     [java] 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
     [java] 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:347)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:346)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:267)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:210)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:170)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:145)
     [java] 	at com.google.gwt.dev.Compiler.run(Compiler.java:129)
     [java] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:99)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
     [java] 	at com.google.gwt.dev.Compiler.main(Compiler.java:106)
     [java]    [ERROR] Unexpected error while processing XML
     [java] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:371)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:68)
     [java] 	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:418)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:346)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:267)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:210)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:170)
     [java] 	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromClassPath(ModuleDefLoader.java:145)
     [java] 	at com.google.gwt.dev.Compiler.run(Compiler.java:129)
     [java] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:99)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
     [java] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
     [java] 	at com.google.gwt.dev.Compiler.main(Compiler.java:106)

BUILD FAILED
/home/prabhu/workspace/projects-2015/GWTOff/src/com/test/build.xml:46: Java returned: 1

Total time: 4 seconds

**Comment by prabhugade** [comment]
Hi,
It is working fine if all the jar files are using 1.0.7.
Thank you.

**Comment by realityforge** [comment]
That is quite odd. I can not see any changes between those two versions that would cause this (See https://github.com/realityforge/gwt-appcache/compare/1.0.7...1.0.8). Did you ever track further details on what could have caused this?

**Comment by realityforge** [comment]
Unfortunately I am unable to reproduce this so I am assuming this was a local configuration problem. 

Feel free to re-open the issue if it still exists and you are able to give more information on how to track it down.
