### ISSUE TITLE
manifest file needs a unique identifier to force recaching after recompile

### ISSUE THREAD

**Issue by legen-daer** [realityforge/gwt-appcache#15]
Hi,
when the GWT app is recompiled it seems the .appcache files do not change, if the permutations are the same. That means the client will not recache the files listed in the .appcache manifest file, because the manifest file is identical to the manifest downloaded the last time.

Therefore I think during compilation each .appcache file should get a unique comment string that changes with every recompile (something like date+random number). This way we can assure that clients recache all files after recompile of the app.

Is there a reason for not doing that? 

I am using this nice library for a small app with MGWT2.0 and after storing mgwt density in a cookie it works pretty well.

Regards,
Ingo

**Comment by realityforge** [comment]
The library used to do this at one stage but it was removed as we realized that if the GWT app is recompiled and the javascript actually changes then the filename for the generated javascript will change and thus the manifest will change. So thus there is no need to change the manifest. 

Do you see anything wrong with this strategy?

**Comment by legen-daer** [comment]
If the javascript file name really changes then it is ok. I assumed the file name is generated form the permutations, not the javascript content and did not check it. Thanks for clarifying this.
