### ISSUE TITLE
maven version range for gwt-appcache-server not working

### ISSUE THREAD

**Issue by paulfrench** [realityforge/gwt-appcache#9]
In my pom if I use...

```
<dependency>
  <groupId>org.realityforge.gwt.appcache</groupId>
  <artifactId>gwt-appcache-server</artifactId>
  <version>1.0.7</version>
</dependency>
```

...I get the artifact

If I do....

```
<dependency>
  <groupId>org.realityforge.gwt.appcache</groupId>
  <artifactId>gwt-appcache-server</artifactId>
  <version>[1.0.7,2)</version>
</dependency>
```

...it does not find the artifact. I assume some maven meta data has not been built correctly somewhere when uploading the artifact??

The below works but obtains me the 1.0.6 version.

```
<dependency>
  <groupId>org.realityforge.gwt.appcache</groupId>
  <artifactId>gwt-appcache-server</artifactId>
  <version>[1.0.6,2)</version>
</dependency>
```

Maybe it is something wrong with our nexus server but thought to check with you.

Cheers

**Comment by realityforge** [comment]
I don't actually use Maven much (and never use version ranges regardless) so I have not run into this issue. I downloaded the two poms from Maven central and did a diff

```
system garkbit:~/Code $ diff gwt-appcache-server-1.0.*
11c11
<   <version>1.0.6</version>
---
>   <version>1.0.7</version>
```

As expected, the only difference is the version value. Maven Central regenerates their cached indexes every new deploy so I would assume that there indexes are up to date.

So it may be your local nexus? Not sure.

**Comment by realityforge** [comment]
Closing as no response and no actionable data
